---

- hosts: testbuntus
  become: True
  tasks:

    - name: SETUPCLIENTS | Install openvpn client
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - openvpn
        - resolvconf

    - name: SETUPCLIENTS | Copy configuration file
      synchronize:
        src: "/nfsshare/clients/{{ inventory_hostname }}.ovpn"
        dest: "/etc/openvpn/client.conf"
      delegate_to: "{{ groups['docker_swarm_manager'] | first }}"
      become_flags: '-HE'

    - name: SETUPCLIENTS | Enable Autostart openvpn
      lineinfile:
        dest: /etc/default/openvpn
        regexp: '^#\s*AUTOSTART="all"$'
        line: 'AUTOSTART="all"'
        backrefs: yes
        state: present

    - name: SETUPCLIENTS | Restart OpenVPN
      service:
        name: openvpn
        state: restarted

    - name: SETUPCLIENTS | GatherFacts again
      setup:

    - name: SETUPCLIENTS | Get OpenVPN IP\'s
      set_fact:
        vpn_ip: "{{ ansible_tun0.ipv4.address }}"

    - debug:
        msg: "VPN_IP: {{ vpn_ip }}"
