---

# Setup Docker Swarm
- hosts: docker_swarm_manager,docker_swarm_worker
  become: True
  vars:
    - docker_swarm_network_interface: enp0s8
  tasks:
    - name: MAIN | Setup Docker and Docker Swarm
      include_role:
        name: docker-swarm

    - name: MAIN | Setup NFS
      include_tasks: ./test-setup/setup-nfs.yml

    - name: MAIN | Setup OpenVPN
      include_tasks: ./test-setup/setup-openvpn.yml

    - name: MAIN | Test Clients
      include_tasks: ./test-setup/test-clients.yml
